---
output:
  pdf_document:
    includes:
      in_header: 
        - _tex/preamble.tex
header-includes:
  - \chead{Übungsaufgaben 6 - Univariate Deskriptivstatistik II}
---

```{r, echo=F}
library(knitr)
opts_chunk$set(fig.width = 5, fig.height = 3.8, fig.align = "center", 
               comment = NA, strip.white = TRUE, 
               out.width = ".8\\textwidth",
               warning = FALSE, message = FALSE, 
               background = "springgreen3")
#knit_theme$set(knit_theme$get()[9])
options(digits = 7)
```

## Vorbereitung

Bitte führen Sie zur Vorbereitung folgende Schritte aus:

1.  Starten Sie RStudio.
2.  Löschen Sie den Workspace. 
3.  Setzen Sie das Arbeitsverzeichnis dort, wo Sie Ihre Daten abgelegt haben: \menu{Session > Set Working Directory > Choose Directory}.
3.  Öffnen Sie ein R-Skript.
4.  Nachdem Sie die Aufgaben bearbeitet haben, speichern Sie das Skript unter einem geeigneten Namen ab.

## Aufgabe 1 - Verteilung eines Merkmals

(i) Untersuchen Sie die Form der Verteilung der Prokrastination (`prok`) anhand von Modalwert, Median und Mittelwert.

(ii) Stellen Sie die Verteilung auch grafisch mithilfe eines Histogramms dar. Zeichnen Sie in diesem Histogramm den Mittelwert ein. Färben Sie die Balken lila. Benennen Sie das Diagramm mit dem Titel "Histogramm von Prokrastination". Benennen Sie die Y-Achse mit "Häufigkeit" und löschen Sie den Titel der X-Achse.

## Aufgabe 2 - z-Transformation

Transformieren Sie die Variable `lz.2` (entsprechend der z-Transformation). Interpretieren Sie den z-transformierten Wert der 11. Person.

## Aufgabe 3 - Streuungsmaße

(i) Berechnen Sie, mit welchem Alter die Personen ihr Abitur gemacht haben. Berechnen Sie dann die Standardabweichung für dieses Alter.

(ii) Zentrieren Sie die neu gebildete Variable und bestimmen Sie zur Überprüfung Mittelwert und Standardabweichung, jeweils auf zwei Nachkommastellen gerundet. 

(iii) Bestimmen Sie, mit welchem Alter die meisten Teilnehmenden ihr Abitur gemacht haben mithilfe eines Befehls.













