---
header-includes:
- \usepackage{fancyhdr}
- \usepackage{menukeys}
- \usepackage{enumitem}
- \pagestyle{fancy}
- \fancyhf{}
- \chead{Codebook}
- \rhead{\thepage}
output:
  pdf_document
---

```{r, echo=F}
library(knitr)
opts_chunk$set(fig.width = 5, fig.height = 3.8, fig.align = "center", 
               comment = NA, strip.white = TRUE, 
               out.width = ".8\\textwidth",
               warning = FALSE, message = FALSE, 
               background = "springgreen3")
#knit_theme$set(knit_theme$get()[9])
options(digits = 7)
```

[**Übersicht der Variablen im Datensatz Erstis**]{.ul}

+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| Variable             | Beschreibung                                                                                                                                             | Ausprägung              |
+======================+==========================================================================================================================================================+=========================+
| code                 | Probandencode                                                                                                                                            | kontinuierlich          |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| gruppe               | Gruppenzugehörigkeit Wintersemester                                                                                                                      | 1 = Kurs 1              |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 2 = Kurs 2              |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 3 = Kurs 3              |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 4 = Kurs 4              |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| geschl               | Geschlecht                                                                                                                                               | 1 = weiblich            |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 2 = männlich            |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| gebjahr              | Geburtsjahr                                                                                                                                              | kontinuierlich          |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| alter                | Alter                                                                                                                                                    | 1 = ja                  |
|                      |                                                                                                                                                          |                         |
| abi                  | Jahr Erwerb der Hochschulfreife                                                                                                                          | 2 = nein                |
|                      |                                                                                                                                                          |                         |
| kinder               | Haben Sie Kinder?                                                                                                                                        |                         |
|                      |                                                                                                                                                          |                         |
| job                  | Haben Sie einen Nebenjob?                                                                                                                                |                         |
|                      |                                                                                                                                                          |                         |
| berlin               | Leben Sie zurzeit in Berlin?                                                                                                                             |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| wohnort.alt          | Wo haben Sie vor 12 Monaten gelebt?                                                                                                                      | 1 = alte BL             |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 2 = neue BL             |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 3 = Berlin              |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 4 = Ausland             |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| uni1                 | Studienberatung                                                                                                                                          | 0 = nein\               |
|                      |                                                                                                                                                          | 1 = ja                  |
| uni2                 | Bibliotheken                                                                                                                                             |                         |
|                      |                                                                                                                                                          |                         |
| uni3                 | Orientierungswoche                                                                                                                                       |                         |
|                      |                                                                                                                                                          |                         |
| uni4                 | PC-Pool                                                                                                                                                  |                         |
|                      |                                                                                                                                                          |                         |
| uni5                 | Mensa                                                                                                                                                    |                         |
|                      |                                                                                                                                                          |                         |
| uni6                 | Studentische Cafés                                                                                                                                       |                         |
|                      |                                                                                                                                                          |                         |
| uni7                 | Unisport                                                                                                                                                 |                         |
|                      |                                                                                                                                                          |                         |
| uni8                 | Uniparties                                                                                                                                               |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| stim1                | zufrieden                                                                                                                                                | 1 = überhaupt nicht     |
|                      |                                                                                                                                                          |                         |
| stim2                | ausgeruht                                                                                                                                                | 5 = sehr                |
|                      |                                                                                                                                                          |                         |
| stim3                | ruhelos                                                                                                                                                  |                         |
|                      |                                                                                                                                                          |                         |
| stim4                | schlecht                                                                                                                                                 |                         |
|                      |                                                                                                                                                          |                         |
| stim5                | schlapp                                                                                                                                                  |                         |
|                      |                                                                                                                                                          |                         |
| stim6                | gelassen                                                                                                                                                 |                         |
|                      |                                                                                                                                                          |                         |
| stim7                | müde                                                                                                                                                     |                         |
|                      |                                                                                                                                                          |                         |
| stim8                | gut                                                                                                                                                      |                         |
|                      |                                                                                                                                                          |                         |
| stim9                | unruhig                                                                                                                                                  |                         |
|                      |                                                                                                                                                          |                         |
| stim10               | munter                                                                                                                                                   |                         |
|                      |                                                                                                                                                          |                         |
| stim11               | unwohl                                                                                                                                                   |                         |
|                      |                                                                                                                                                          |                         |
| stim12               | entspannt                                                                                                                                                |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| lz13                 | In den meisten Breichen entspricht mein Leben meinen Idealvorstellungen. Meine Lebensbedingungen sind ausgezeichnet. Ich bin mit meinem Leben zufrieden. | 1 = stimme gar nicht zu |
|                      |                                                                                                                                                          |                         |
| lz14                 | Bisher habe ich die wesentlichen Dinge erreicht, die ich mir für mein Leben wünsche.                                                                     | 2 = stimme nicht zu     |
|                      |                                                                                                                                                          |                         |
| lz15                 | Wenn ich mein Leben noch einmal leben könnte, würde ich kaum etwas ändern.                                                                               | 3 = stimme eher zu      |
|                      |                                                                                                                                                          |                         |
| lz16                 |                                                                                                                                                          | 4 = teils/teils         |
|                      |                                                                                                                                                          |                         |
| lz17                 |                                                                                                                                                          | 5 = stimme eher zu      |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 6 = stimme zu           |
|                      |                                                                                                                                                          |                         |
|                      |                                                                                                                                                          | 7 = stimme völlig zu    |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| prok                 | Prokrastination                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| extra                |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| vertraeg             |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| gewiss               |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| neuro                |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| intell               |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| gs.1                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| gs.2                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| wm.1                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| wm.2                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| ru.1                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| ru.2                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| lz.1                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| lz.2                 |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.inh.1            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.inh.2            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.bed.1            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.bed.2            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.bel.1            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| zuf.bel.2            |                                                                                                                                                          |                         |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
